### ISSUE TITLE
Missing support for new ImperativeExpression system in Oxygen

### ISSUE THREAD

**Issue by eliasvasylenko** [eclipse/efxclipse-rt#142]
I'm no expert but it looks like it's just a simple change to `BaseRenderer`. Skip the manual RAT stuff for `MImperativeExpression`s, and pass them through to `ContributionsAnalyzer#isVisible` in the same place as `MCoreExpression`? Well idk there's probably more to it than that.

**Comment by tomsontom** [comment]
Since 3.1 is based on Oxygen we have to implement this support
