### ISSUE TITLE
ci configuration insufficient to build

### ISSUE THREAD

**Issue by wowselim** [eclipse/efxclipse-rt#193]
Hey,
I just forked the repository and committed something. Travis failed with the same message I got on my local machine. Looks like there is a missing maven repository for the `org.eclipse.*`.
I thought I could add the bestsolutions maven repository but the build command doesn't know how to locate the jar since the path seems to be different (`at.bestsolution...` instead of `org.eclipse...`)

Would be nice to be able to build this so that people can contribute :-)

**Comment by wowselim** [comment]
for completeness, this is the error:
```
[ERROR] Cannot resolve project dependencies:
[ERROR]   Software being installed: org.eclipse.fx.osgi.util 3.1.0.qualifier
[ERROR]   Missing requirement: org.eclipse.fx.osgi.util 3.1.0.qualifier requires 'package org.eclipse.fx.core 3.1.0' but it could not be found

```

**Comment by tomsontom** [comment]
Is this on the 3.x branch?

**Comment by wowselim** [comment]
on master

**Comment by tomsontom** [comment]
master is currently completely unstable (there we are switching to a pure maven-build!) so please use 3.x which is the current stable release branch

**Comment by wowselim** [comment]
ok on 3.X:

```
selim@sdincer-pc2:~/git/efxclipse-rt$ git checkout -b "3.X"
Switched to a new branch '3.X'
selim@sdincer-pc2:~/git/efxclipse-rt$ mvn -f releng/org.eclipse.fx.releng/pom.xml clean package integration-test
[INFO] Scanning for projects...
[INFO] Computing target platform for MavenProject: org.eclipse.fx.runtime:org.eclipse.fx.osgi.util:3.1.0-SNAPSHOT @ /home/selim/git/efxclipse-rt/modules/core/org.eclipse.fx.osgi.util/pom.xml
[INFO] Fetching p2.index from http://download.eclipse.org/eclipse/updates/4.7/R-4.7-201706120950/
[INFO] Fetching p2.index from http://download.eclipse.org/eclipse/updates/4.7/R-4.7-201706120950/
[INFO] Adding repository http://download.eclipse.org/eclipse/updates/4.7/R-4.7-201706120950
[INFO] Fetching p2.index from http://download.eclipse.org/efxclipse/targets-nightly/
[INFO] Fetching p2.index from http://download.eclipse.org/efxclipse/targets-nightly/
[INFO] Adding repository http://download.eclipse.org/efxclipse/targets-nightly
[INFO] Adding repository http://download.eclipse.org/efxclipse/runtime-shared-nightly/site
[INFO] Resolving dependencies of MavenProject: org.eclipse.fx.runtime:org.eclipse.fx.osgi.util:3.1.0-SNAPSHOT @ /home/selim/git/efxclipse-rt/modules/core/org.eclipse.fx.osgi.util/pom.xml
[INFO] {osgi.os=linux, osgi.ws=gtk, org.eclipse.update.install.features=true, osgi.arch=x86}
[ERROR] Cannot resolve project dependencies:
[ERROR]   Software being installed: org.eclipse.fx.osgi.util 3.1.0.qualifier
[ERROR]   Missing requirement: org.eclipse.fx.osgi.util 3.1.0.qualifier requires 'package org.eclipse.fx.core 3.1.0' but it could not be found
```

am I missing something??

**Comment by tomsontom** [comment]
I think you used the wrong branch it is a lower-case x => "3.x" not "3.X"

**Comment by wowselim** [comment]
I actually tried both, hence the edit. I still get the same error. I will investigate a bit and get back here.

**Comment by tomsontom** [comment]
th sign that something is fishy is that everything in 3.x should have the version 3.2.0-SNAPSHOT and 3.2.0.qualifier - see https://github.com/eclipse/efxclipse-rt/blob/3.x/modules/core/org.eclipse.fx.osgi.util/META-INF/MANIFEST.MF

**Comment by wowselim** [comment]
the problem was the `-b` parameter in git checkout. It seems to have created a local branch. very embarrassing :--)
