### ISSUE TITLE
FXClassLoader doesn't work properly for Java 10

### ISSUE THREAD

**Issue by qtdzz** [eclipse/efxclipse-rt#215]
When using Java 10, `javafx.embed` is not hooked correctly as it does in Java 9. It throws
```
Unable to locate JavaFX. Please make sure you have a JDK with JavaFX installed eg on Linux you require an Oracle JDK
```

I think the problem is possibly from this https://github.com/eclipse/efxclipse-rt/blob/master/modules/core/org.eclipse.fx.osgi/src/main/java/org/eclipse/fx/osgi/fxloader/FXClassLoader.java#L48

**Comment by tomsontom** [comment]
I've put this now on 3.3.0 although I can not guarantee that I'll have the cycles to fix it.

**Comment by tomsontom** [comment]
@qtdzz you might be interested in #217
