### ISSUE TITLE
Loading OpenJFX-Modules 11 in OSGi

### ISSUE THREAD

**Issue by tomsontom** [eclipse/efxclipse-rt#217]
OpenJFX-Modules will not be shipped in the JRE but need to be added to module-path. We need to find a strategy to install the OpenFX-Binaries at runtime.

**Comment by eliasvasylenko** [comment]
The first Maven snapshots are now available: http://mail.openjdk.java.net/pipermail/openjfx-dev/2018-July/022088.html

They are not shipped with OSGi metadata. In the (likely?) event that they're not interested in adding it, I assume it's just a matter of wrapping and republishing as a p2 artefact somewhere?

**Comment by tomsontom** [comment]
That won't help! JavaFX is designed to run on the module-path, while it might work on the classpath there's no guarantee that it will in future.

**Comment by eliasvasylenko** [comment]
Surely this is true of *any* external dependencies packaged as modules. But until perhaps the next OSGi release specifies a strategy for JPMS interoperation, or unless Eclipse already has a general strategy planned for this, what choice is there?

Recreating the module metadata as bundle metadata will *probably* work. And if it stops working at some point in the future, that can be dealt with in the future, no?

**Comment by tomsontom** [comment]
We are already spinning up a virtual layer for swtfx.jar I think that's the way to go for plain OpenJFX on Java 11 onwards as well.
