### ISSUE TITLE
Drag and Drop TabPane can't be used in FXML

### ISSUE THREAD

**Issue by Adrodoc55** [eclipse/efxclipse-rt#26]
Drag and Drop Support for TabPane uses DndTabPaneFactory instead of a subclass. This prevents the use in FXML.

**Comment by Adrodoc55** [comment]
I fixed this issue locally, but i don't know how to build a jar for org.eclipse.fx.ui.controls in order to test my changes.

When i run maven install on the pom.xml in eclipse I get an exception (see below). I have no experience with maven, I am only used to gradle, how can I do this?

```
[ERROR] Cannot resolve project dependencies:
[ERROR]   Software being installed: org.eclipse.fx.ui.controls 3.0.0.qualifier
[ERROR]   Missing requirement: org.eclipse.fx.ui.controls 3.0.0.qualifier requires 'package org.eclipse.fx.core 3.0.0' but it could not be found
[ERROR] 
[ERROR] See http://wiki.eclipse.org/Tycho/Dependency_Resolution_Troubleshooting for help.
[ERROR] Cannot resolve dependencies of MavenProject: org.eclipse.fx.runtime:org.eclipse.fx.ui.controls:3.0.0-SNAPSHOT @ C:\Users\Adrian\Programme\ws-neon\org.eclipse.efxclipse\bundles\runtime\org.eclipse.fx.ui.controls\pom.xml: See log for details -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MavenExecutionException
```

**Comment by Adrodoc55** [comment]
Ok I found out how to test it, I fixed some things and now i want to push it. Do i push it to master, do I make a custom branch? In both cases i get (prohibited by Gerrit). My Credentials are correct and I have agreed to the ECA. The [main site](https://wiki.eclipse.org/Efxclipse#How_to_contribute) is not very specific on what to do.

**Comment by tomsontom** [comment]
Unfortunately this is not up-to-date because we are just in the transition phase - contributions are now done through github-pull requests - see https://guides.github.com/activities/contributing-to-open-source/#contributing
