### ISSUE TITLE
Allow E4FX headless application

### ISSUE THREAD

**Issue by ckeimel** [eclipse/efxclipse-rt#49]
Currently the application closes when the last e4-window ist removed from the application.

In our application, we also open legacy windows in our code that are hard to break up into parts fot the application model. We would like to have the possibility to keep the e4fx application running while we are only displaying legacy windows. From here we can then reactivate e4-windows (set toBeRendered=true or add them to the children of application) that are currently not showing .

A headless mode like this could also be usefull for other applications, that do not directly show a window on startup but wait for a specific event before displaying a ui.

**Comment by tomsontom** [comment]
when you say Legacy windows you mean non JavaFX windows or are those JavaFX Windows just not controlled by e4?

**Comment by ckeimel** [comment]
I mean JavaFX Windows (Stages) that are not controlled be e4 (no MWindow)

**Comment by tomsontom** [comment]
Can you give this change a spin. If you run with this flag the only option to shutdown is to call IWorkbench.close (or the RestartService)

**Comment by ckeimel** [comment]
Thanks, but this doesn't solve our use case. I don't think it is necessary to call Platform.setImplicitExit(false) because we always have an open stage. The Problem is that the stage is not managed by the e4 application.

**Comment by ckeimel** [comment]
I have created a demo for the issue. When you start the application you will see the "Main E4 Window". With "Open external stage" you can open multiple new windows. None of these are managed by the e4 application model. 

The "External Stage" has a button "Open Main Window". there can only be one "Main Window", so as long as it is open it will be brought to the front. This works fine. When the main window is closed I expect toBeRendered to be set to false, so that I can re-show the window with setToBerendered(true), see MainWindowHandler.

But the application never gets this far, as the e4 platform has shut down. The command to open the main window can not be found anymore.

[test.external.stage.app.zip](https://github.com/eclipse/efxclipse-rt/files/983380/test.external.stage.app.zip)

**Comment by tomsontom** [comment]
We can not set the toBeRendered = false for the last top-level window otherwise we'd have a problem on the next start where no top-level window is rendered.

**Comment by tomsontom** [comment]
Looking at your example the problem with commands is NOT that anything has been shutdown but that you use the IEclipseContext of the MWindow to create the external stage (see ```ExternalStageHandler```).

If you close the e4 window we destroy its IEclipseContext and now the CommandService you use is working on a disposed ```IEclipseContext```. I've now modified ```CommandService``` to proactively throw an exception if you operate on a disposed instance.

To fix your command problem the best solution is most likely that you create your own ```IEclipseContext``` for the window opened and not controlled by e4.

```java
@Execute
public void execute(IEclipseContext context) {
  context = context.get(MApplication.class).getContext().createChild();
  ExternalWindow window = ContextInjectionFactory.make(ExternalWindow.class, context);
  window.showAndWait();
}
```
As explained in the comment above NOT setting toBeRendered=false is a desired thing for the last one you need to change your code to

```java
if( window.getWidget() == null ) {
	engine.createGui(window);
}
WWindowImpl windowImpl = (WWindowImpl)window.getWidget();
Stage theStage = windowImpl.getWidget();
if (theStage == null) {
	return;
}
Platform.runLater(() -> theStage.toFront());

```
