### ISSUE TITLE
Project SETUP Help

### ISSUE THREAD

**Issue by inamaurya** [eclipse/efxclipse-rt#64]
**I am using Eclipse RCP as a platform for development.
I am developing an e4 application using JavaFX as an UI Technology.
Please suggest me that which technology I should for modeling, Like- EMF or others.**

Thanks,
Ajay

**Comment by martinbluehweis** [comment]
EMF would fit into your technology stack very well, but the best choice depends on your requirements.

Please note: this is an issue tracker and not the right place for questions. For that please go to a forum e.g. https://www.eclipse.org/forums, see the documentation https://wiki.eclipse.org/Efxclipse, ...

**Comment by inamaurya** [comment]
Thanks a lot
