### ISSUE TITLE
Need Help for Processor in E4

### ISSUE THREAD

**Issue by inamaurya** [eclipse/efxclipse-rt#91]
Dear Tom,

I am facing a problem while adding a menu entry to File Menu in Eclipse IDE 4.6 using the model processor.
This problem is exactly like the one mentioned in https://www.eclipse.org/forums/index.php/t/499577/

Do we have any solution for this?

In the example below..
When I try to print Menu, it is coming as null.
My Idea was to manipulate any IDE UI element through the processor. Is it possible in eclipse IDE (Being a not pure E4 application)?

Request your suggestion on this…

Thank you very much.
import org.eclipse.e4.core.di.annotations.Execute;
import org.eclipse.e4.core.di.annotations.Optional;
import org.eclipse.e4.ui.model.application.MApplication;
import org.eclipse.e4.ui.model.application.ui.advanced.MPerspectiveStack;
import org.eclipse.e4.ui.model.application.ui.menu.MMenu;
import org.eclipse.e4.ui.workbench.modeling.EModelService;

public class ModelProcessor {
@nAmed("menu:org.eclipse.ui.main.menu")
private MMenu menu;

   public ModelProcessor() {
          System.out.println("Model Processor constructor called");
   }

   @Execute
   public void execute(MApplication application, EModelService modelService, @Optional MPerspectiveStack perspectiveStack ) {
          System.out.println("ModelProcessor:execute called");
          System.out.println(menu);
   }
}

Thanks,
Ajay

**Comment by tomsontom** [comment]
This is a issue tracker and not a help forum please ask at the appropriate place for help
