### ISSUE TITLE
create target platform   fail   

### ISSUE THREAD

**Issue by QingMings** [eclipse/efxclipse-rt#94]
Eclipse for RCP and RAP Developers

Version: Oxygen Release (4.7.0)
Build id: 20170620-1800

I try  3.0.0

![image](https://user-images.githubusercontent.com/22107668/27812488-e0561726-60a1-11e7-9ed2-b58c56e81929.png)

I also  try 2.4.0  ,
![image](https://user-images.githubusercontent.com/22107668/27812525-2355f5fa-60a2-11e7-8684-5e14144ca481.png)

**Comment by tomsontom** [comment]
Did you follow - https://wiki.eclipse.org/Efxclipse/Tutorials/Tutorial4 (important point is Step 7)

**Comment by QingMings** [comment]
thanks , it helpful for me
